skip_branch_with_pr: true
skip_tags: true

install:
  - choco install -y InnoSetup
  - git submodule update --init --recursive

build_script:
  - build.cmd

artifacts:
  - path: setup.exe
    name: Very Sleepy installer
  - path: symbols.7z
    name: Debugging symbols

test_script:
  - tests\tests\run_tests.bat

deploy:
  provider: GitHub
  tag: appveyor
  release: appveyor
  description: 'Latest build from AppVeyor CI'
  auth_token:
    secure: qqtZWL+oz2DPdI31/TicJ9/SKk+GP18zlWMNbZ21WA49P+MnNksyKAplu0PyeYQo
  artifact: setup.exe, symbols.7z
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master
